wallets = {
    1:"YOUR_EVM_ADDRESS_1",
    2:"YOUR_EVM_ADDRESS_2",
    3:"YOUR_EVM_ADDRESS_3",
    4:"YOUR_EVM_ADDRESS_4",
    5:"YOUR_EVM_ADDRESS_5",
    6:"YOUR_EVM_ADDRESS_6",
    7:"YOUR_EVM_ADDRESS_7",
    8:"YOUR_EVM_ADDRESS_8",
    9:"YOUR_EVM_ADDRESS_9",
    10:"YOUR_EVM_ADDRESS_10",
    11:"YOUR_EVM_ADDRESS_11"
}